---
- name: SELinux状態変更時に必要に応じてOSを再起動
  shell: sleep 2 && shutdown -r now "Ansible reboot"
  async: 1
  poll: 0
  changed_when: true

- name: 再起動完了まで待機
  local_action: wait_for
  args:
    host: "{{ ansible_host }}"
    port: 22
    state: started
    search_regex: OpenSSH
    delay: 30
    timeout: 600

